version: '3.3'
services:
  db1:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'rigemdb1'
      MYSQL_USER: 'avbravo'
      MYSQL_PASSWORD: 'denver16'
      MYSQL_ROOT_PASSWORD: 'denver16'
    ports:
      - '3306:3306'
    volumes:
      - db1-data:/var/lib/mysql

  db2:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'rigemdb2'
      MYSQL_USER: 'avbravo'
      MYSQL_PASSWORD: 'denver16'
      MYSQL_ROOT_PASSWORD: 'denver16'
    ports:
      - '3307:3306'
    volumes:
      - db2-data:/var/lib/mysql

volumes:
  db1-data:
  db2-data:
